"""Dependency injection for the KnowProbe API."""

from __future__ import annotations

import secrets
from functools import lru_cache
from typing import Annotated

from fastapi import Depends, Header, HTTPException, Request, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

from knowprobe.core.config import Settings, get_settings
from knowprobe.utils.logging import get_logger

logger = get_logger("api.dependencies")
security = HTTPBearer(auto_error=False)


# ---------------------------------------------------------------------------
# Settings
# ---------------------------------------------------------------------------
@lru_cache(maxsize=1)
def _cached_settings() -> Settings:
    """Load and cache application settings.

    Settings are cached per-process to avoid repeated file I/O.
    """
    return get_settings()


def get_app_settings() -> Settings:
    """FastAPI dependency: inject application settings."""
    return _cached_settings()


SettingsDep = Annotated[Settings, Depends(get_app_settings)]


# ---------------------------------------------------------------------------
# Request context
# ---------------------------------------------------------------------------
async def get_request_id(
    request: Request,
    x_request_id: Annotated[str | None, Header(alias="X-Request-ID")] = None,
) -> str:
    """Extract or generate a request correlation ID.

    Priority:
        1. X-Request-ID header
        2. Existing request.state.request_id (set by middleware)
        3. New UUID generated by middleware
    """
    if x_request_id is not None:
        request.state.request_id = x_request_id
        return x_request_id
    return getattr(request.state, "request_id", "unknown")


RequestIdDep = Annotated[str, Depends(get_request_id)]


# ---------------------------------------------------------------------------
# Common query parameters
# ---------------------------------------------------------------------------
class CommonQueryParams:
    """Reusable query parameters for list endpoints."""

    def __init__(
        self,
        page: Annotated[int, Depends()] = 1,
        per_page: Annotated[int, Depends()] = 20,
        sort_by: Annotated[str | None, Depends()] = None,
        sort_order: Annotated[str, Depends()] = "desc",
    ) -> None:
        if page < 1:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="page must be >= 1",
            )
        if per_page < 1 or per_page > 100:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="per_page must be between 1 and 100",
            )
        self.page = page
        self.per_page = per_page
        self.sort_by = sort_by
        self.sort_order = sort_order.lower()


CommonParamsDep = Annotated[CommonQueryParams, Depends()]


# ---------------------------------------------------------------------------
# API key authentication (optional)
# ---------------------------------------------------------------------------
async def optional_api_key(
    settings: SettingsDep,
    authorization: Annotated[HTTPAuthorizationCredentials | None, Depends(security)] = None,
) -> bool:
    """Optional API key validation.

    Returns True if no API key is configured (open access).
    Returns True if a valid bearer token is provided.
    Raises 403 if an invalid token is provided.
    """
    configured_key = settings.api.api_key
    if not configured_key:
        if (
            settings.app.environment.lower() == "production"
            and not settings.api.allow_unauthenticated
        ):
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="API authentication is required but no API key is configured",
            )
        return True

    if authorization is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Bearer token required",
            headers={"WWW-Authenticate": "Bearer"},
        )

    if not secrets.compare_digest(authorization.credentials, configured_key):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Invalid API key",
        )
    return True


OptionalAuthDep = Annotated[bool, Depends(optional_api_key)]
